# Generated by Django 5.1.1 on 2024-09-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="post",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
